### ISSUE TITLE
readme instructions are incorrect

### ISSUE THREAD

**Issue by jantari** [arcticicestudio/nord-dircolors#15]
In the README.MD,

the following command is suggested:

```bash
test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)
```

but it won't work ( tested on Debian 10, bash 5.0-4 ).
![image](https://user-images.githubusercontent.com/25607767/79736072-8b138000-82f9-11ea-9fde-050c6acf8d35.png)

The quotes need to be ommited and the command should be:

```bash
test -r ~/.dir_colors && eval $(dircolors ~/.dir_colors)
```

The problem is explained here: https://serverfault.com/a/417255

**Comment by arcticicestudio** [comment]
Hi @jantari :wave:, thanks for your contribution :+1:

Well recognized, variable/parameter expansion are always are always a great pitfall (even though the screenshot of the command in the README is correct) 😄 
Would you like to submit a PR o fix this in this repository as well as for [the port project documentations][docs]?

[docs]: https://github.com/arcticicestudio/nord-docs/tree/develop/content/docs/ports/dircolors/installation

**Comment by ghost** [comment]
#19 is open to address this.
