### ISSUE TITLE
Profile not listed in "profiles"

### ISSUE THREAD

**Issue by ev-agelos** [arcticicestudio/nord-dircolors#5]
I cloned the repo and ran the nord.sh but I do not see any profile in profiles :/

(I use mint 18)

**Comment by arcticicestudio** [comment]
This is **not** a terminal emulator theme. It provides a dotfile for the GNU core util [`dircolors`](https://www.gnu.org/software/coreutils/manual/html_node/dircolors-invocation.html#dircolors-invocation) which is a color setup for the Linux core command `ls`.
If your're looking for color profile for your terminal emulator you should check out the [Getting Started](https://github.com/arcticicestudio/nord-dircolors#getting-started) README section and install the specific terminal emulator theme.

By the way, this repository does not contain a `nord.sh` file but a `install.sh`. Are you sure you've created this issue in the correct repository?

**Comment by ev-agelos** [comment]
oh :O u are right im in wrong repo, sry! (probably i was searching through ur repos and ended up in the wrong one, was looking for nord-gnome-terminal one)
Well the issue remains for me but i should do it in the correct repo sry :|

Edit: im so confused xD, i wanted only the dircolors for ls not the whole theme in the first place, so my mistake is i cloned the "theme" repo and ran nord.sh which didnt work but anyway didnt want that so i will clone this one for dircolors and try the install.sh and if doesnt work ill come back :)

**Comment by arcticicestudio** [comment]
Closing this stale issue for now since it is invalid for this repository and seem to be resolved by the author.
